### PR TITLE
Add a rationale and mission statement

### PR DESCRIPTION
**Pull request by mstade**
This is an attempt to clearly define Rhumb's mission statement, it's responsibilities, and some fundamental requirements.

### CODE REVIEW

**Comment by mstade** [comment]
@sammyt I'd love some of your input on this, if you have a chance. @pemrouz your input is of course also always interesting.

**Comment by pemrouz** [comment]
TIL Rhumb! Lol, that makes a lot more sense now - thanks @mstade :+1:.

Where you touch on the following:

> match URIs in O(1) time, possibly at the expense of slower registration

It might be worth explaining a little bit more how this fits in with a new class of trie-based routers, [like routington](https://github.com/pillarjs/routington#routington):

> Routington is a trie-based URL router. Its goal is only to define and match URLs. It does not handle methods, headers, controllers, views, etc., in anyway. It is faster than traditional, linear, regular expression-matching routers, although insignficantly, and scales with the number of routes.

> The purpose of this router isn't for performance, but to bring more structure to URL routing. The intention is for you to build a framework on top either in node.js or in the browser.

I've also been doing some experiments with rhumb/routing and have a few ideas to share with y'all, but they are outside the scope of this PR.

**Comment by mstade** [comment]
Heh, well TIL there's such a thing as trie basen routers. The JS community's faiblesse for turning data structures into marketing buzzwords never fails to amaze. Oh well. I don't quite understand what you mean when you ask "how it fits in" – I mean, it's a router. It routes things I guess?

**Comment by mstade** [comment]
> I've also been doing some experiments with rhumb/routing and have a few ideas to share with y'all, but they are outside the scope of this PR.

Please do!!

**Comment by pemrouz** [comment]
> Heh, well TIL there's such a thing as trie basen routers. The JS community's faiblesse for turning data structures into marketing buzzwords never fails to amaze. Oh well. I don't quite understand what you mean when you ask "how it fits in" – I mean, it's a router. It routes things I guess?

Well, routers have often tended to be built on top of lots of regexp, and I think that's what most people think of them as. I was just thinking a note to explain a bit more how it works under the hood, i.e. rather than regexps, it builds a tree, and this is primarily for more structure rather than performance, etc. That's what really sets apart this approach from things like [page.js](https://visionmedia.github.io/page.js/) (which has a similar basic API, but uses [path-to-regexp](https://github.com/pillarjs/path-to-regexp) under the hood)..

**Comment by mstade** [comment]
Ah, right, I see. I'd be reluctant to put this in the mission statement though, because it's an implementation detail. The O(1) guarantee is to assert that you'll have a linear performance degradation correlation to the input, both in terms of stored routes and in terms of URI input to the matching function. This performance is and has to be a key feature I think, in order to be a robust tool for use in REST style systems; how it's achieved is less relevant.

That said, it probably should be documented *as well*, in order to make people wanting to contribute understand the mechanics. It's just not relevant to the mission statement. I'll open up a different PR for that though, it's a great suggestion! (Or if you feel so inclined, go ahead and contribute! ;o))

**Comment by pemrouz** [comment]
:+1: CONTRIBUTING.md, perhaps?

**Comment by mstade** [comment]
That's a good idea, thanks!

**Pull request merged**
